# Site settings
title: Jolly Zhao / 赵磊
description: Jolly's resume and treasure chest
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jolly Zhao
user_description: I’m now doing my second-year Master in Computer Science at University of Southern California. I’m expected to graduate in 2021 summer.
user_title: Student/Software Developer/Trader
email: zhaolei@pm.me
twitter_username: Jolly23
github_username:  Jolly23
gplus_username:  Jolly23

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
